---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: assignment-demo
type: Opaque
stringData:
  POSTGRES_USER: appuser
  POSTGRES_PASSWORD: AssignmentPassword**009
  POSTGRES_DB: assignmentdb